MAGISK_MODULE_HOMEPAGE=https://www.mpfr.org/
MAGISK_MODULE_DESCRIPTION="C library for multiple-precision floating-point computations with correct rounding"
MAGISK_MODULE_LICENSE="LGPL-2.0"
MAGISK_MODULE_DEPENDS="libgmp"
MAGISK_MODULE_BREAKS="libmpfr-dev"
MAGISK_MODULE_REPLACES="libmpfr-dev"
MAGISK_MODULE_VERSION=4.1.0
MAGISK_MODULE_REVISION=2
MAGISK_MODULE_SHA256=0c98a3f1732ff6ca4ea690552079da9c597872d30e96ec28414ee23c95558a7f
MAGISK_MODULE_SRCURL=https://mirrors.kernel.org/gnu/mpfr/mpfr-${MAGISK_MODULE_VERSION}.tar.xz
MAGISK_MODULE_EXTRA_CONFIGURE_ARGS="ac_cv_header_locale_h=no"
