MAGISK_MODULE_HOMEPAGE=https://www.mpfr.org/
MAGISK_MODULE_DESCRIPTION="C library for multiple-precision floating-point computations with correct rounding"
MAGISK_MODULE_LICENSE="LGPL-2.0"
MAGISK_MODULE_DEPENDS="libgmp"
MAGISK_MODULE_BREAKS="libmpfr-dev"
MAGISK_MODULE_REPLACES="libmpfr-dev"
MAGISK_MODULE_VERSION=4.0.2
MAGISK_MODULE_REVISION=2
MAGISK_MODULE_SHA256=1d3be708604eae0e42d578ba93b390c2a145f17743a744d8f3f8c2ad5855a38a
MAGISK_MODULE_SRCURL=https://mirrors.kernel.org/gnu/mpfr/mpfr-${MAGISK_MODULE_VERSION}.tar.xz
MAGISK_MODULE_EXTRA_CONFIGURE_ARGS="ac_cv_header_locale_h=no"
