MAGISK_MODULE_HOMEPAGE=https://libcxx.llvm.org/
MAGISK_MODULE_DESCRIPTION="DL Standard Library"
MAGISK_MODULE_LICENSE="NCSA"
MAGISK_MODULE_VERSION=$MAGISK_NDK_VERSION
MAGISK_MODULE_ESSENTIAL=yes

magisk_step_post_make_install() {
	cp "$MAGISK_STANDALONE_TOOLCHAIN/sysroot/usr/lib/${MAGISK_HOST_PLATFORM}/libdl.a" $MAGISK_PREFIX/lib
}
