--- fzy-1.0/Makefile	2018-09-23 22:05:55.000000000 +0000
+++ ./Makefile	2020-10-16 20:23:39.736704491 +0000
@@ -11,7 +11,7 @@
 INSTALL_PROGRAM=$(INSTALL)
 INSTALL_DATA=${INSTALL} -m 644
 
-LIBS=-lpthread
+LIBS=-lc -ldl
 OBJECTS=src/fzy.o src/match.o src/tty.o src/choices.o src/options.o src/tty_interface.o
 THEFTDEPS = deps/theft/theft.o deps/theft/theft_bloom.o deps/theft/theft_mt.o deps/theft/theft_hash.o
 TESTOBJECTS=test/fzytest.c test/test_properties.c test/test_choices.c test/test_match.c src/match.o src/choices.o src/options.o $(THEFTDEPS)
