MAGISK_MODULE_HOMEPAGE=https://github.com/json-c/json-c/wiki
MAGISK_MODULE_DESCRIPTION="A JSON implementation in C"
MAGISK_MODULE_LICENSE="MIT"
MAGISK_MODULE_VERSION=0.15
MAGISK_MODULE_SRCURL=https://s3.amazonaws.com/json-c_releases/releases/json-c-${MAGISK_MODULE_VERSION}.tar.gz
MAGISK_MODULE_SHA256=b8d80a1ddb718b3ba7492916237bbf86609e9709fb007e7f7d4322f02341a4c6
MAGISK_MODULE_BREAKS="json-c-dev"
MAGISK_MODULE_REPLACES="json-c-dev"
MAGISK_MODULE_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_INSTALL_PREFIX=${MAGISK_PREFIX} \
-DBUILD_SHARED_LIBS=OFF \
"

mmagisk_step_pre_configure() {
	LDFLAGS=" -llog"
}
