MAGISK_ANDROID_BUILD_TOOLS_VERSION=29.0.2
MAGISK_NDK_VERSION_NUM=21
MAGISK_NDK_REVISION=d
MAGISK_NDK_VERSION=$MAGISK_NDK_VERSION_NUM$MAGISK_NDK_REVISION

test -f "$HOME/.magiskrc" && . "$HOME/.magiskrc"

: "${ANDROID_HOME:="${HOME}/lib/android-sdk"}"
: "${NDK:="${HOME}/lib/android-ndk"}"
: "${MUSL_TOOLCHAIN:="${HOME}/lib/android-musl"}"
