MAGISK_MODULE_HOMEPAGE=https://github.com/dylanaraps/neofetch
MAGISK_MODULE_DESCRIPTION="Simple system information script"
MAGISK_MODULE_LICENSE="MIT"
MAGISK_MODULE_MAINTAINER="Muhammad Herdiansyah @konimex"
MAGISK_MODULE_VERSION=6.0.0
MAGISK_MODULE_SHA256=264a7689561bb498f97f10231959bdd8f7c873671bac2ffb660de9a5863b1c76
MAGISK_MODULE_SRCURL=https://github.com/dylanaraps/neofetch/archive/${MAGISK_MODULE_VERSION}/neofetch-${MAGISK_MODULE_VERSION}.tar.gz
MAGISK_MODULE_BUILD_IN_SRC=yes
MAGISK_MODULE_PLATFORM_INDEPENDENT=yes

