MAGISK_MODULE_HOMEPAGE=https://github.com/dylanaraps/neofetch
MAGISK_MODULE_DESCRIPTION="Simple system information script"
MAGISK_MODULE_LICENSE="MIT"
MAGISK_MODULE_MAINTAINER="Muhammad Herdiansyah @konimex"
MAGISK_MODULE_VERSION=7.1.0
MAGISK_MODULE_SHA256=58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7
MAGISK_MODULE_SRCURL=https://github.com/dylanaraps/neofetch/archive/${MAGISK_MODULE_VERSION}/neofetch-${MAGISK_MODULE_VERSION}.tar.gz
MAGISK_MODULE_BUILD_IN_SRC=yes
MAGISK_MODULE_PLATFORM_INDEPENDENT=yes

